packages: []

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  bufferutil: set this to true or false
  core-js: set this to true or false
  utf-8-validate: set this to true or false
  esbuild: true
